console.log('-----------------------------------------------------------------');
var myFullName;
console.log('Before Initialization :' + myFullName);
myFullName="Vishwajeet";
console.log('After Initialization :'+  myFullName);
myFullName = "Vishwajeet Vasantrao Jamdade"
console.log('After Updation :' + myFullName);
console.log("-------------------------*******----------------------------------");
var myLove;
myLove="I Love Only JS";
console.log(myLove);
console.log("-------------------------*******----------------------------------");
var firstName;
firstName="Vishwajeet";
console.log("First Name :" +firstName);
var lastName;
lastName="Jamdade";
console.log("Last Name :" +lastName);
var age;
age="23";
console.log("Age :" +age);
var address;
address="Sangli";
console.log("Address :" +address);
var pinCode;
pinCode="416408";
console.log("PinCode :" +pinCode);
var gender;
gender="Male";
console.log("Gender :" +gender);
var ismarried;
ismarried="False";
console.log("Is married :" + ismarried);
console.log("-------------------------*******----------------------------------");
